spring.application.name=Transaction_Risk_API

spring.datasource.url=jdbc:mysql://localhost:3306/Database_Name
spring.datasource.username=root
spring.datasource.password=your_DB_Pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true